# Electric Text Configuration Example
# This file can be placed in one of the following locations:
# - ./config.yaml
# - ~/.electric_text/config.yaml
# - /etc/electric_text/config.yaml
# Or you can set the ELECTRIC_TEXT_CONFIG environment variable to point to a custom location

# Default settings for providers
provider_defaults:
  default_model: "ollama:llama3.1:8b"

# Logging configuration
logging:
  level: "ERROR"

# HTTP logging configuration
http_logging:
  enabled: true
  log_dir: "./http_logs"

# Shorthand configuration for providers and models
# Environment variables take precedence over these values
shorthands:
  # Provider name shorthands
  provider_names:
    ollama: "lma"
    anthropic: "ant"
    openai: "oai"

  # Model shorthands: model name -> shorthand
  models:
    ollama:
      "llama3.1:8b": "31"
    anthropic:
      "claude-3-7-sonnet-20250219": "37"
    openai:
      "gpt-4o-mini": "4o"