# ------------------------------
#  Logs
# ------------------------------
EVENT_AWAITED = "event_awaited"
EVENT_PROCESSED = "event_processed"
EVENT_RECEIVED = "event_received"
EVENT_STREAMED = "event_streamed"
STREAM_CANCEL_RECEIVED = "stream_cancel_received"
STREAM_CANCELED = "stream_canceled"
STREAM_CLOSED = "stream_closed"
STREAM_CREATED = "stream_created"
STREAM_FAILED = "stream_failed"
STREAM_MISSING = "stream_missing"
STREAM_QUEUED = "stream_queued"
STREAM_REMADE = "stream_remade"
STREAM_REQUESTED = "stream_requested"
STREAM_STARTED = "stream_started"
TASK_CANCEL_FAILED = "task_cancel_failed"
TASK_CANCELED = "task_canceled"
TASK_CANCELLED = "task_cancelled"
TASK_CHUNK_STREAMED = "task_chunk_streamed"
TASK_CLEARED = "task_cleared"
TASK_COMPLETED = "task_completed"
TASK_MISSING = "task_missing"
USER_TEXT_RECEIVED = "user_text_received"
